# Basic MangoHud config with toggle
# no_display                # Hide by default
toggle_hud=F12           # Use F12 to toggle overlay visibility


fps
cpu_stats
gpu_stats
ram
vram
engine_version
frame_timing
wine

# Appearance settings (optional)
font_size=24
position=top-left
background_alpha=0.5
